### ISSUE TITLE
[Bug]: Search bar not working properly

### ISSUE THREAD

**Issue by nhan000** [obsidianMkdocs/obsidian-github-publisher#12]
### Describe the bug

On [Obsidian Mkdocs Publisher](https://obsidianmkdocs.github.io/obsidian_mkdocs_publisher_docs/), search can't look for note title or content. Only search for Headings works.

### How to reproduce ?

Use [Snippets and tools - Obsidian Mkdocs Publisher](https://obsidianmkdocs.github.io/obsidian_mkdocs_publisher_docs/Template/snippets%20and%20tools/) as an example.

Search for title of the note "Snippets and tools" doesn't return the page
![image](https://user-images.githubusercontent.com/85216095/177229698-137a7ba6-a1bf-491a-8168-86032f03d82e.png)

Search for content of the page "Automatically convert the" also doesn't return the page
![image](https://user-images.githubusercontent.com/85216095/177229747-228a3acc-c182-4bef-8b3b-6c2062705839.png)

Search for headings work
![image](https://user-images.githubusercontent.com/85216095/177229786-1c24dee2-8257-4c38-ab5c-3c0faf159332.png)

Also, what's the difference between the results that have and don't have this icon ![image](https://user-images.githubusercontent.com/85216095/177229887-5c8bd6a4-3dbb-4b5a-b683-4857c173e0a7.png) next to it?

### Configuration

N/A

### OS

Windows

**Comment by Mara-Li** [comment]
Please open an issue on the [Template](https://github.com/Mara-Li/mkdocs_obsidian_template) as said in the bug form.

**Comment by Mara-Li** [comment]
Yeah, the search is a little strange here. Dunno how it search for title, filename and quote.
I think two things : 
- By default, material mkdocs add the filename/title frontmatter in the document’s heading 1. 
- But, the material search only search in CONTENTS, aka the other heading, maybe frontmatter title and file’s contents. 

So searching a filename (and not the heading) using quote won’t work.
