### ISSUE TITLE
[Bug]: I tried to install this plugin from within Obsidian, but it failed

### ISSUE THREAD

**Issue by janc-pxl** [obsidianMkdocs/obsidian-github-publisher#13]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Workflow

Obsidian plugin 💠

### Describe the bug

I clicked on Install in obsidian and nothing happens. Other plugins work fine

### Configuration

not relevant

### OS

MacOS

**Comment by janc-pxl** [comment]
It worked when I installed it via  BRAT

**Comment by Mara-Li** [comment]
I will check! Thanks for the report.

**Comment by Mara-Li** [comment]
Fixed in 3.10.1, lowered minappversion until official release of Obsidian 0.15.x
