### ISSUE TITLE
[Bug]: Status bar element being repeatedly added

### ISSUE THREAD

**Issue by Mearman** [obsidianMkdocs/obsidian-github-publisher#6]
### What part of the workflow is concerned ?

Obsidian plugin

### Describe the bug

![CleanShot 2022-06-12 at 23 03 35](https://user-images.githubusercontent.com/1331872/173255530-4ffd36c5-4dec-4781-b473-b7d628f6dc98.png)

![CleanShot 2022-06-12 at 23 05 01](https://user-images.githubusercontent.com/1331872/173255539-12facb71-a6db-4784-b673-859f9c1bc94a.png)

### OS

MacOS

**Comment by Mara-Li** [comment]
What, pretty strange. I never caught that during my testing. How much note did you send ?

**Comment by Mara-Li** [comment]
Also, is your Obsidian up to date ? I can't repro it :(

**Comment by Mearman** [comment]
..... quite a lot of notes
it's all up to date

**Comment by Mara-Li** [comment]
Strange, it doesn't happen with 3 notes... Tbh I don't have so much file to send, as I want to avoid exploding my Obsidian.

**Comment by Mara-Li** [comment]
I tryed with 26 notes, and same results : I don't have this bug...

**Comment by Mara-Li** [comment]
Can't repro this bug with 60 notes :/
