### ISSUE TITLE
[Bug]: Images don't get uploaded

### ISSUE THREAD

**Issue by nyejon** [obsidianMkdocs/obsidian-github-publisher#7]
### What part of the workflow is concerned ?

Obsidian plugin

### Describe the bug

Hi,

Nice plugin, exactly what I was looking for :D

I have managed to get everything working, except that it seems to delete the images from my repository, and doesn't upload the ones from Obsidian.

Maybe I have missed something?

### OS

MacOS, Windows

**Comment by Mara-Li** [comment]
Strange, i dont have these problem on my side. What is your configuration to repro this ?

**Comment by Mara-Li** [comment]
Oh, found my error, thanks for the info !

**Comment by nyejon** [comment]
Here are the settings from Obsidian:

![image](https://user-images.githubusercontent.com/17871768/173618828-687505b7-d8ac-4d19-aabc-0b685a553f4d.png)

**Comment by Mara-Li** [comment]
Hello! I pushed an quick fix in the last update. Please, update your plugin :)

**Comment by nyejon** [comment]
Thanks! That does seem to fix the images being deleted in the images folder.

Now the problem with the links to the images is that the image path is not appended when replacing the Wikilinks with MDlinks.

**Comment by Mara-Li** [comment]
I will check that ! Can you open a new issue ?

**Comment by nyejon** [comment]
Sure :)
