### ISSUE TITLE
[FR]: Use Obsidian subfolder as root

### ISSUE THREAD

**Issue by todistantlands** [obsidianMkdocs/obsidian-github-publisher#9]
### What part of the workflow do you want to improve ?

Obsidian plugin

### Is your feature related to a problem ?

I would like to sync a subfolder of my Obsidian vault to the root of my git repo using the Obsidian Path folder reception setting. Because the Obsidian path is mapped relative to the vault root folder (eg. vault/), anything in the subfolder (eg. vault/sub/) gets uploaded to repo/sub/.

### What solution do you want to see ?

Option in in plugin config to designate a subfolder of the vault for syncing to repo.

So for example you could plug in in vault/sub/ as the base folder for sync. That way the sync flow would be vault/sub/ --> repo/ and vault/sub/a/ --> repo/a/

### Describe the alternative you've considered

I have looked into creating a separate vault specifically for syncing to the repo but moving files from other vaults into the sync one creates extra steps I would like to remove.

### OS

Windows

**EDIT:** I have looked into this a little further, it looks like there may also be underlying issues with the Obsidian Path option. If you leave "default folder" blank for that setting it fails to sync entirely...

**Comment by Mara-Li** [comment]
So, if I understand well, the idea is to "remove" the root path of your vault in the repo path ? 
I can add a new setting where you put the path you want to "remove" in the new path. 

For example : 
```
remove path: [text]
Put the path you want to remove for reception
```

But It will be strange if you use another folder. Why don't use the frontmatter options ? There are more options and you can use meta-edit to add the category. Note that metaedit allow bunch editing metadata if you have a folder note!

**Comment by todistantlands** [comment]
Thank you, this is perfect! :)

**Comment by Mara-Li** [comment]
Yeay! In fact, it's usefull in my workflow for update the docs xD
